const strings={
    SOLUTIONS:'SOLUTIONS',
    INDUSTRY:'INDUSTRY',
    TECHNOLOGY:'TECHNOLOGY',
    CAREERS:'CAREERS',
    ABOUT:'ABOUT',
    CONTACT:'CONTACT',
    VALOR1TITLE:'NEARSHORE ADVANTAGE',
    VALOR1DESC:'OUR GEOGRAPHICAL PROXIMITY IS A HUGE PLUS FOR YOUR AGILE SOFTWARE DEVELOPMENT, WE ENSURE SUCCESSFUL SOFTWARE DEVELOPMENT PROJECT BASED ON EFFICIENT COMMUNICATION BETWEEN TEAMS AND CUSTOMERS.',
    VALOR1RES:'Can’t get any closer than nearshore.Hire highly talented engineers in time zones near to you.',

    VALOR2TITLE:'COST ADVANTAGE',
    VALOR2DESC:'THE COMPANY OFFERS TO OUR CUSTOMERS THE BEST RATES AND THE IDEAL ENVIRONMENT FOR SUCCESSFUL PROJECTS.\n WE PROVIDE REALLY COMPETITIVE RATES AND DISCOUNTS FOR ALL OUR CONTRACTS.\n WE ALSO HAVE SEVERAL CUSTOMER RETENTION STRATEGIES THAT WILL KEEP YOU SATISFIED WITH US.',
    VALOR2RES:'Best investment, best rates for software development.',

    VALOR3TITLE:'QUALITY & EFFICIENCY',
    VALOR3DESC:'OUR COMPANY VALUES AND PROMOTES SMART WORK AND CONTINUOUS IMPROVEMENT IN ORDER TO PROVIDE HIGH QUALITY IN EVERY PROCESS AND PRODUCT.\n OUR TEAMS APPLY HIGH QUALITY CODING STANDARDS AND ADVOCATE THE USE OF AGILE METHODOLOGIES IN ORDER TO ENSURE THE QUALITY OF EVERY DELIVERY.',
    VALOR3RES:'We strive for high quality in every aspect of our work and relationship.',

    VALOR4TITLE:'OUR PEOPLE',
    VALOR4DESC:'CONFIDENTIALITY & INTELLECTUAL PROPERTY POLICIES DOING BUSINESS WITH MASTERMIND IS THE SAME AS WITH ANY OTHER US BASED COMPANY.\n WE ENSURE CONFIDENTIALITY AND PROPER USE OF YOUR INFORMATION THROUGH THE FOLLOWING POLICIES: AS A US BASED COMPANY ALL CUSTOMER’S AGREEMENT ARE US CONTRACTS.\n YOUR INTELLECTUAL PROPERTY IS PROTECTED BY DOCUMENTED, COMPREHENSIVE LEVELS OF PHYSICAL AGREEMENTS.\n ALL EMPLOYEES ARE SUBJECT TO STRICT IP PROTECTION AND CONFIDENTIALITY POLICIES ENFORCED BY NDAS.',
    VALOR4RES:'Expand your team with seasoned professionals.',

    VALOR5TITLE:'CONFIDENDIALITY POLICIES',
    VALOR5DESC:'OUR DEVELOPERS ARE CAREFULLY SELECTED AND TRAINED WITH THE GOAL OF IMPROVING THE LEARNING CURVE PROCESS.\n WE HIRE DOERS WE HIRE PEOPLE YOU CAN TRUST WE ALSO TAKE INTO ACCOUNT THAT HIRING GOOD WRITERS AND COMMUNICATORS ARE CRITICAL FOR THE BUSINESS SUCCESS WE KEEP GROWING THE SKILLSET OF OUR DEVELOPERS THROUGH THE COMPANY’S TRAINING PLAN WHICH MATCHES THE PROJECTS REQUIREMENTS AND EMPLOYEE’S POTENTIAL.',
    VALOR5RES:'We guarantee the confidendiality and secure use of any sensitive information of your business.',
}

export default {
    STRINGS:strings,
}